[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "daphne -b 0.0.0.0 -p 8000 attandance_app_mul.asgi:application"
sleepApplication = true
[deploy.multiRegionConfig.us-west2]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
