from .base import *  # noqa
import os

DEBUG = False

# Expect explicit ALLOWED_HOSTS in env
_hosts = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h for h in _hosts.split(',') if h]

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_SECONDS = 31536000
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'

