# Generated by Django 5.1.6 on 2025-02-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('device_ip', models.GenericIPAddressField()),
            ],
        ),
    ]
